<!-- Modal -->
<div class="BiddingPriceMessage" id="exampleModalCenter">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header mx-auto">
                <h5 class="modal-title" id="notificationTitle">Modal title</h5>
            </div>
            <div class="modal-body py-2">
                <p id="notificationMessage"></p>
            </div>
            <div class="modal-footer">
                <button id="close_notif" onclick="show_hide_notification(false)" type="button" class="btn btn-primary"> Understood </button>
            </div>
        </div>
    </div>
</div>

