<div class="paragraphs">
    <div class="row">
        <div class="col-12 pl-1 py-2 d-inline-flex bg-light">
            <img src="Images/<?php echo $view->auction[4];?>.jpg" class="auction_image border-link img-responsive mr-md-1 mr-sm-2 mr-xs-2 rounded" alt="...">
            <div class="mt-3 pl-3 pl-lg-1">
                <div class="content-heading"><h4> <?php echo $view->auction[3]; ?></h4></div>
                <p class="text-success mb-0">Ends in <?php echo $view->auction[1] . " at " . $view->auction[2]; ?> </p>
                <p class="mt-0 mb-0">Location <?php echo $view->auction[0]; ?></p>
                <p class="mt-0">Number of paintings: <span class="text-primary"><?php echo $view->numberOfData; ?></span></p>
                <h6 class="blockquote-footer text-danger mt-1">Ends in <?php echo $view->auction_expiration . " days !! "; ?> </h6>
            </div>
        </div>
    </div>
</div>
