<?php require('template/header.phtml') ?>
<div class="container-fluid accessDetails_pages mt-1">
    <h2 class="mt-5 text-info text-center"><?php if($view->numberOfBids === 0) echo "There are no bids in basket, place some bidding first." ?></h2>
    <table id="bid_table" class="table table-striped table-bordered table-warning table-hover text-center mt-5">
        <caption class="text-success"> You have <?php echo $view->numberOfBids ?> bids in basket.</caption>
        <tr>
            <th class="text-primary">Bid ID</th>
            <th class="text-primary">Item ID</th>
            <th class="text-primary">Your Price</th>
            <th class="text-primary">Current Bid Price</th>
            <th class="text-primary">Bid Placed Date</th>
            <th class="text-danger">Customise Bids</th>
        </tr>
        <?php
            foreach ($view->myBids as $bid){
                echo '<tr> <td class="text-danger">' . $bid->getBidID() .
                    '</td> <td>' . $bid->getItemID() .
                    '</td> <td>' . $bid->getUserPrice() .
                    '</td> <td>' . $bid->getBidPrice() .
                    '</td> <td>' . $bid->getBidDate() .
                    '</td> <td> <a class="btn btn-light py-1 px-2" href="single_item.php?id=' .  $bid->getItemID() .'"> Edit Bid </a></td>' .
                    '</td> <td> <a id="rm" class="btn btn-danger py-1 px-2" onclick="remove_bid_from_basket(' . $bid->getBidID() .', this)"> Remove </a></td></tr>';
            }
        ?>
    </table>
</div>
<script src="JavaScript/user_basket.js"></script>
<?php require('template/footer.phtml') ?>
