<?php require('template/header.phtml') ?>


<div class="container home_page pb-5 pt-4">
    <div class="my-5 border border-right border-top-0 border-bottom-0 ">
        <h6 class="mt-2 text-center text-light"> Discover Worlds Most Precious LOTs </h6>
        <h1 class="home-Title text-muted text-center"> Timed Online Auction</h1>
        <figure class="d-flex justify-content-center">
            <img class="img-responsive img-fluid rounded w-25" src="Images/hammar-1.png" alt="Hammer">
            <img class="img-responsive img-fluid rounded w-25" src="Images/hammar-2.png" alt="Hammer">
        </figure>
        <p class="text-muted text-center mt-1">Competition is the key to win</p>
        <h1 class="text-center text-success mt-2"> SOLD <i class="fa fa-check"></i> </h1>
    </div>
</div>



<?php require('template/footer.phtml') ?>
