<?php require_once("Views/template/header.phtml");?>
<div class="container-fluid mt-5 d-flex justify-content-center accessDetails_pages ">
    <div class="bg-white align-self-center p-5 border rounded">
        <h1 class="">Ops it seems like something wrong occurred <span class="fa fa-info-circle text-danger"></span></h1>
        <h1 class="text-center">Try again in few seconds <span class="fa fa-grin-alt text-success"></span></h1>
    </div>
</div>
<?php require('Views/template/footer.phtml') ?>