<!DOCTYPE HTML>
<html>
<head>
    <title> JavaScript Missing </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href='https://fonts.googleapis.com/css?family=Creepster' rel='stylesheet'>
</head>
<body>
<div class="container-fluid mt-5 d-flex justify-content-center accessDetails_pages ">
    <div class="bg-white align-self-center p-5 border rounded mt-5">
        <h1 class="text-center">In order to use this website your javascript must be enabled.<span class="fa fa-info-circle text-danger"></span></h1>
        <h1 class="text-center">Navigate to your browser settings and ensure JavaScript option is active.<span class="fa fa-grin-alt text-success"></span></h1>
    </div>
</div>
</body>
</html>