<footer class="py-3 mt-5">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center flex-column flex-md-row border-bottom pb-2">
            <h5 class="ml-0 ml-md-3 mb-0 text-primary">Quality Talks</h5>
            <ul class="nav justify-content-center">
                <li class="nav-item"><a class="nav-link px-2" href="mailto:someone@example.com">Contact Us</a></li>
                <li class="nav-item"><a class="nav-link px-2" href="http://aee953.poseidon.salford.ac.uk/webdev/About.html">About Us</a></li>
                <li class="nav-item"><a class="nav-link px-2" href="http://aee953.poseidon.salford.ac.uk/webdev/index.html">Educational Site</a></li>
            </ul>
        </div>
        <div class="d-flex justify-content-center align-items-center justify-content-md-between flex-column flex-md-row mx-3 mt-3">
            <div class="d-flex"><a class="mr-2" href="#"><i class="fab fa-facebook"></i></a><a class="mr-2" href="#"><i class="fab fa-linkedin"></i></a><a href="#"><i class="fab fa-twitter"></i></a></div>
            <div class="d-flex mt-3 mt-md-0">
                <p class="mb-0 small text-muted">&copy; 2021 Raman Suliman. All right reserved.</p>
            </div>
        </div>
    </div>
</footer>
</div>
<script src="JavaScript/live_search.js"></script>
<script src="JavaScript/notifications.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>