<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $view->pageTitle; ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="CSS/bootstrap-5.0.0-alpha3-dist/css/myStyle.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href='https://fonts.googleapis.com/css?family=Creepster' rel='stylesheet'>
    <noscript><meta http-equiv="refresh" content="0; url=Views/Forms/noJavaScript.phtml" /></noscript>
    <script> let tokenKey = '<?php echo $_SESSION["URLtoken"]; ?>'; var user_id = '<?php echo $user->getID(); ?>';</script>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar header navbar-expand-lg navbar-light sticky-top" role="navigation">
        <a class="navbar-brand d-lg-none" href="#"><img class="logo" src="Images/site-logo.svg" alt="logo"></a>
        <button class="navbar-toggler border border-warning" type="button" data-toggle="collapse" data-target="#navigations-02"><span class="fa fa-bars text-warning"></span></button>

        <div class="collapse navbar-collapse" id="navigations-02">
            <div class="mr-xl-auto d-lg-block d-none log-parent">
                <a class="navbar-brand d-flex justify-content-center text-success" href="#">
                    <img class="logo" src="Images/site-logo.svg" alt="logo">
                </a>
            </div>
            <ul class="navbar-nav menu nav-justified mr-xl-0 mr-lg-auto">
                <li class="nav-item"><a class="nav-link menu-link" href="index.php"> Home </a></li>
                <li class="nav-item"><a class="nav-link border-link menu-link" href="auctions.php"> Auctions </a></li>
                <?php
                    if($user->isLoggedIn())
                    {
                        echo '<li class="nav-item"><a class="nav-link border-link menu-link" href="basket.php"> <span class="fa fa-shopping-cart"></span>Basket </a></li>';
                    }
                    if($user->isAdminLogged())
                    {
                        echo '<li class="nav-item"><a class="nav-link border-link menu-link" href="admin.php?bids"> Admin </a></li>';
                    }
                ?>
            </ul>
            <!-- Search form -->
            <form class="form-inline justify-content-end search_text mr-0" method="post" action="search.php?">
                <div>
                    <input class="form-control search-bar mr-2" onfocusout="setTimeout(clearViewArea, 150)" onkeyup="getData(this.value)" id="searchBar" name="pattern" type="text" placeholder="Search Items" aria-label="Search" maxlength="20">
                    <input type="hidden" id="keySearch" name="key">
                    <div class="conta"><ul class="list-group" id="searchViewArea"></ul></div>
                </div>

                <input class="form-check-input" type="checkbox" onclick="changeImageStatue(this.checked)" id="imageVisibility">
                <label class="form-check-label text-white mr-1" for="flexCheckDefault">Image</label>
                <button class="btn btn-light mr-2 border-info py-1 px-2" type="submit" name="search"> <span class="fa fa-search"></span> </button>
                    <?php
                    if($user->isLoggedIn() || $user->isAdminLogged())
                    {
                        require_once("Views/Buttons/btn_logout.phtml");
                    }
                    else
                    {
                        require_once("Views/Buttons/btn_login.phtml");
                    }
                ?>
            </form>
        </div>
    </nav>

